``.......``````...--------.`..`.`.---.``.:/::/ohhyo++//oy:``...------..``                       `                                        ```   ```  ````-hmdddddddddddddddddmmmmmmmmdddhyyddhyyyhhyyyyyh
......`````````````.-----.........``...``-----:+sssoo+os/` .::::://:-.```                                                           `````````````````````-:/oyhdddhhyyssooo++//://////+oyhhdddhyyddhyyyh
```````````````````............``````..``..```.........--.``.---:::--.``                             ```..://////:::---..``````````````````````````````.........---------------------:::+yhhddyhhhdmdhhh
``````````````` ````````````  `              ``````````````````````````                             ````..-:::///+++//:.``````````````````````````..-:::::::-----::::::-----------::::://+hdhddhhhhdmmmd
`````````````````` ````                                                                                    `````````...``````...````````````````..:/+oooo++////////::::::::----:::::::///+odddddmhhmdddm
.........`````````````````                                                                                       ````````.-.-::-...```````````..-+o+ooooooooo++++//////::::::::::::::////++sdddddmdhdmmm
-----:----------:-----...`..``````````````````````````   `                                                 ```````````-::/o++o+o+/-...........-:osso+++++++++++++++/////////::/::///////++++ydhdddmmddmm
`````...............--..........---....................`+dhysoo++++/::::/o:               ``          `````````....-/osyyhdyso+/:::-.......--:+ssoos++///////////////////////////////++++oo+ohddmdmmdNmm
                                 ```````````````````````yNNNNNmmNmddyossyhy````````````...```````` `..```..--:://+syddmhy+/-...--::-------://:/+osyyssooo++++++++++++++++++++++++++++ooooooooohddmdmmmNN
                                                        hmNNNmmmNmddyyyyhmh`        ```````````.-``...--://:::--:/+oo/--.....--:/+++/++++oo:`````.-:+oosssssssssssssssssssooooooooooooossooosssdmmmmmmmm
                                                        dmNmmddmmmmdhhyhdmh                    `-........````````.-.....---://+syhhysssoo++``````````-+osoooosssyyyyyyyyysssssssssssssssssssssshmmmmmmdh
                                                       `dNNNmhdmNmmmhyyhdmd`                `.```.--://+o```````:+`  `://+osyhmmhooyo+++++:          -dddddhysooosssssssyyyyyyyyyyyyyyyyyyyyyyyhmmmdhyyy
                                      `                .mNNNmhdmNmmmhhyhmmm`          -..`-+ossyyyyyyhdmm.`````:sy:`.:osyyyyydhyo:os++++/:`          /mmmddmmdddhyssoossssssssyyyyyyyyyyyyyyyyyhddhyyyhh
``````````                                             .mmNNmhdmNmdmdhyhmmm.          o+++yssooohyyhhdmdo..--:+syyyssyyyyyo:/yssyyy- `               +ddmmmddmmmmmmmmdhhyyyssssssssssssyyyyhddddddhyyhdd
````````````````````````````````..                     /mNNNmddmmmddysssydd/`````````.ysyssoosoosoo++///:::---..:shyyhysysosyysoso.             `````...-+oydmmmmmmmmmmmmmmmmmmdddhhhhddmmmdddddddhyyhdd
`                             `.:-                     -dmmmmhhddddddhhhhmm+..-......----...````````             `:+syys:`....```        ````.......```````..-/oshdmmmmmmmmmmmmmmmdhhhddddddhhhhhhyyyhdd
o.                             `--                     .dmNNdssdmdmNmdhddmN-```                                     `..`        ```````..-..............````````..--:+oyhddddddddddhhhhdddhhhhhhhhyssyhd
d/                             `--                     .dmNNdyymmmmNmdddmmm                                               `.---......-------.............................-/oyhdddddhyhhhhhhhyyyhyyyssyyh
:`                             `--                     `hmmNmhydmmmNmmddmNh            .::.                              `---:::---::+//:-------.....--....------:::----.....-:+osyyhhhhhhhyyyyhyyssssyy
                               `-.                     `hmNNmhhdmdmNmdddmNs          `/yhhy/                        `/:-.--:::/ooossyy/:-::-:---------::-::::::::::///:::::--.....---:/+osssyyhhhhyysyyh
                               .--                      ymmmmhhdmddNmmddNm:         ``+hhhy:   ```````````  `````````-::/+++oossyyhdh/:::/:::::::::::://////////:://////////::::-----.....----:::///++oo
                               `.-                      :hdmmddmmmmNNNmmmh.``....-----:////:://////////+/......----::::////+++oosss+/:::://////////////++oooooooooooooooooo++++////::-------------------
                                ``     ` ```````.......-:/+oooossssssooo+::::://////////+++++oo+osoooooo/.--++++++oooossssyyyyys+/////////////++////++++ooooooossssoosssossosssoooo+++//:::::::::::::---
                             `````......---------:::-:::://///////////:::::::://////////+oooooo+ooooooos/.-/yyyhhhhhhhhhhhhyo/:/++ooo+++++++++++++++++++++ooooooossosssssssssssssooooooo+++///////////::
                   `````````.........----------------::::::::////////:::::::::////////++++ooooooosssss+/-`-//////:::----s+/::/+osyyyyo++++++++++++oooooooooooosssossoossssssssssssosooooooooo+++++++++//
                  ````````````...........------------::::::::://///////////////+++++ooooossssssssyyyy/               `.-----.--:/oyhhhyysssooooooooooooooossyhhddysddhhyyysssooooooooooooooooooooo+o++++
``````                   `````````````............---::////////+o+//+++++o+osssssssssssoooo+++//////:`          `:-..--::--....----:/+oo++++oooossssssoo+yddmmmmmdoddddddddddhhysssoooooooooooooooooooo+
``..```````````````````````````````````````````----/+/+/+/+++/::/+::/::::/:+//++::..````                      -`//-----:::----------.--....--:oyhysssssooshhddhyyyhddddddddddddddddhhysooo+ooooooooooooo
`..```````````````....`.`````````````````````.:.-:///:::::+/:/::-::----:/:..::.::/:--```                     -:::::::::-:--:::.------------:/shhdhyhhyssyhmdso+/:+syyhdddddddddddddddddddhysso+++++ooo++
............................................-o+:///:::://-:+:::-:::::--:-::--/:/+::--::::.``````````````````:+/:------:::-:::/:--::::::::::+yhmdhhhhhyosyhs+//:::::::://+osyhhdddddhdddddddddhhyyoo+++++
---..............................-........-/so::/:+++:..--://:..---::---/-:/+++/:-:++++o+/-.``......../.-:-+ss+:::::::::-::::://:/::::::::syddyyyyyhhyyhys/::::::/::-------:::/osyyyhhhhhddddddddddhhyoo
---.................-....--...........-+o++///sso/:--......--:--:/::++:-///+/++::-.--/o:--/.--..------///+ooso::::::/::::/:////::::/::/:/yyhhysyssyhyyhmh//::/::::::-------:-:::::://////+oossyhhddddddh
---..--..--.....-..--.---.-..........-+hdhds-::::--.-------`-//:-/++///+++:--:+y+:-/:/o:-.::/o+++++oo+/ooosss/::::://+/::////://::://+//omhhyyyhhhhhhmmy///////:::::--::::::::::::::::::::---::://++oooo
-------------.--------::::::::::::::/ohyyys+-/:------:::://--///////--:-://-:-./o/:oooo+o++oyh++sso/o/osyyyh+++///////++++///::////+///+ommdddhhhdhdyds/////////////::/:////////::::::::::::-:::-:::::--
----:--------/+oooooooo+ooo++++o++++//ys+s+:/+--::::-:::++:/:++//:::-----:+:-//+oso++/:/+syyy/ooo++//+yhdddh+ooo//////++++++//::////+///+hmmmdddmddho////+/////////////////+++///://://::::::::::::::-::
-----------/oooooooo+++++++++++++++o+/ssoso+++/:////://:/+///+/://oo//+//+o+ossso+sso/--:/yyo:/oo///:/shyshhoooo++////++/:://///////+///+odmdddmmy+//////+///////////////////+/+/////////:::::::::::::::
--:--------/ooooooo++++++++++++++++soosyhsoooo++//:::://::/::/://::syosso/+shhs/::ohdo:://shso/ooyo/:+ssyyhhyooo+o+//////////:///++/+///++ommmmmmy/////////+///+++o//////////////////+/////////:::::::::
-..-.....--+ooooo+o++++++o++++++++/yy//hy:/++///o/:://:::+/o/:::--/yhhyo//++ohy:-:-:sh++yhs/hmhs+os++syshhhhhhs+++o+/+o++++/+/+++o+++++++++sdmmmmms+///////+///+ooo+//////////////////////////////:://::
.........-:ooooo+++++++++++++++++++//::ss:://+soso//+/:-:syhoo//o++syys+::/-:oy:://ohhysyo+:+ydh++sosyyo+shhhhy++/+++yhhhsoo++oo+o+++ooo++++odmmmmms+++////////++++///+//////////////////////////::////:
-.....-.--:oooooooo+++o++++++++++++::/+hso+++ossyo++/+o+shhyossyoosssyhy+/ooyyyssyyho+yyso/-:/hs/sssyysoosyyyhys++//+++os++++sosyyyhyyyyssoooosydmNmo+++////////+////////////////////////:://///////////
-.....-.--:oooooooooooooo+oo+oo++++/:+oyoo+++osso+ssoosyysoooyhyyso/+syhhshysoyhdyso:+sshso+ssos+yhyohdhyssshhhyoo+ooooooooydhyhhhhyhyyyyssssyhddMMNmyo+////+//////////////////////////////////:///://:/
.-......--+sooooooooooooo+ooooo++oosyysssoo++++++o+ossso+//+//soso+//::sydso/+o+hds/:::/ss+hh+ohshddyshdhyo+ohhhhyssydddhyyyydmmmmmdhhyysssssyhhdddhhdhs+/////++///////////////////////////://///////:::
.......--:/sooooooooooooooooooooooooyssoyssoso++ooooossys++/+/osyyo+o:+yhhso:/::ymh+osyhydds+:/yydmmdhhdhhysshhhhdhhyydmdhyh/+sdmdmNNNNmhyyyssssoooo++///://++/+///+////+///////////:////:::://:///////:
:-....---:+yoooooooooooooooooooooooosshhysssoooos+//:oosys+soossyhhhdhhsyhhs+ooooydhyhs+oyms///++sddhhhydssyyyhhhdddysyNNdhysooyyhhyyyhhyyyyhhyssooosso+/::::/oo+///////+/////////://::::/:::::::::///::
:------:::/yooooooooooooooooooooossssohyssssoosossosyssshyhhhyysyhhhyo+/oyhhhyhysyhmh+://ohyoo+osshyhsyyddsyyyyhhyhhyssyNNmdhyyssssyhyyyyssyyhyyyyyysssooo/+///++ooo+++/+////://///////::/:::::::-::::::
-:------::/ysoosssossssooosssssssssssssyyyyyyossssssyysoyssyoooooyyds+//-:syhso://ohy+++oyydysyyyyyyyyyhdhyyyyyyhhyyhhhsshmmNmdhysssyyyhddhyysysyyyyhyhooo/soooo-/syyssso+//////:::////::::::/:::--:::::
.---------:osoossssssssssssssssssssyyyyyhhysyysssydysssyyyhysoo+/sydhsyyyyhhhyo/++yhhhhyooyhyhhhhhhhhhhhhhhhhhhhhhdhhdmdyyddmmmdmddddhhoyhyyyyssysyysyyooooo+:::--ohhhhyhyyyo+////:://::::::::::::::::::
.....----:-+yooooooossssssssssssssyyyyyyyhmhyyyyyyhyys+ssyyddyhhhyyhddhhooshmmyhysyhddsosooyhhhhhhhhdddddddddddhddddhhhddhhdddddddddddddhhyyyyyssyyyysssssoss/::--+hdddddhhhhdhso+///::::::::::::::---:-
``...----::+ysoooossssssssssssssyyyyyyyhhhhhhhyyhhddyyyyyddddhysoosdmmhooo+ohddyso+yhhmmddhhhhhhyyhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyso+++++o+++++//++++o::--.:yddddddhhddddddhys+//:::::::::::::--:
```..---:--/+yooooooossssssssssssyyyyyyhhhhdddmdhhhmNNmhyyydmmmdhohhmmmmdhyydmNmmdhhdddddhhhyyyyyysssssssyyyyyyyyysyysssssssssssssyysssssss+/////:////:::/:::--.-.-oddhhhhhhhhhhhdhhhhhs+//:::::::::::::
`...-.------/yoooooooooosssssssssyyyyyyyyhhddddmmmmmNNNNmddmNNNNmmdhddmmmmmmmmdddddhhhhhhyyyyyyssssssssssosssssssssssssssososssssyssssssssss+::-:------------..`.../hhhhhhhhhhhhhhhhhhhhhhyo+//:::::::::
-..........--osoooooooooooooosssssssyssyyyhhhhhhhhddddddddddddddhhhhhhhhhhyyyyyyyyyysssssssssssoossoosssssssssssossssssosso+osooosoo+oooosooso:.-.--..........`````-yhhhhhhhhhhhhhhhhhhhhhhhhyso+/::::::
.............:yooooooooooooooooossssssssssssssssyyyyyyhhhyhhhhhyyyyyyysssysssssssssoooo++++ooooooosssooooosssossoosssso+oooossoo++oo++++++++oo+:...........`````````oyyyyyyyyyyyhhyhyyyyyyyyyyyyyso+/:--
`.....-.-....-/y+ooooooooooooooooososssssssssssssssssyyyyyyssssssssssssosoooooooo+++oooo++ooooooooooo+ooooooosooooosssssooooooo+oooooooooo+++oo+/.....``.```.-`    `:ooooooooossssssssssssssssssssoo+/-:
...`......``..-sso++oooooooooooooooooooooossssssssoooosoosooosooooo+ooo+ooo+++++//+///+//++++oo++//+++++++oooooooosssoosooooosoooooosooooo+oo+oooo-......`...``     `+oooooooooooooooooooooooooo+++//:::
``````.```````-/h++++++++++oooooooooooooooooooooooooossssssooooooo++++++///+//////++++++///+/+oo+++ooo++ooooooooooooosssssooooooososssssoooosoooooo:-...--....````   /+++++++++ooooooooooo++++++///:-..:
```````````.```.+y++++++++++++o+oo++o+ooo+++o++oooooooooooo++o+ooo++++/////+++/+oo+/+++++/+++++ooo+++++ooooooooooossooosssssssossssssssooososssooooo/.........-``  ` -++++++++++++++oooooooo++++///:--::