--.`.-.`.-``..``..``..``.```.```` `````````````````````````````````````````````````..`````` `` `` `` `` `` ``  `  `` `` `````````````````````````````````````````` `` ````````````+dssosoooo/` ``  `````
.--`.-.`.-.`.-``..``..``.```.``````````````````````````````````````````````````````..`````` `` `` `` `` `` `` `` ``` ````````````````````````````````````````````` `` ```````````.shsssssooo:  `````````
.--``.-``-.``-```.``..``..``.```.``````````````````````````````````````````````````..````````` ```````` `` ```````````````````````````````````````````````````````````.``````````.dyssssssoo.```````````
..-.`.-.`.-``-.``-.``.``..``.```.``````````````````````````````````````````````````..`````````````````````````````````````````````````````````````````````````````````.`````````.:dyssssssso````````````
`.--`.-.`.-``..``..``..``.```.`````````````````````````````````````````````````````.-`````````````````````````````````````````````````````````````````````````````````.`````````.ohyyyyyyyy+````````````
..--``--``-.`.-``..``..``.```.`````````````````````````````````````````````````````.-````````````````````````````````````````````````````````````````````````````````..``````....ymyysyysss-````````````
...-.`.-``..``-.`.-``..``..``.```.`````````````````````````````````````````````````--.```````````````````````````````````````````````````````````````````````````````.````````..-ddyyssssso.```````````.
-`.-.`.-.`.-``..``-.``.``..``.```.`````````````````````````````````````````````````.-.``````+oo-`````````````````````````````````````````````````````````````````````-```````...+ddyyssyss+````````````.
-..--`.-.`.-.`.-``..``..``.``..``.```.`````````````````````````````````.```````````-:.`````-+o//`````````````````````````````````````````````````````````````````````-``````....smhyyyyyss/```````````..
-.`.-.`--``-.`.-``..``..``.``..``.```.```.`````````````````````````````.```````````...`````./+/-``.``````.``````````````````````````````````````````````````````````..````......hmyyyyyyys-```````````..
--`.-.`.-.`.-``-.`.-``..``..``.``..``.```.`````````````````````````````..-`````````-/:``````-+:```..````````````````````````````````````````````````````````````````..````.....:ddyyyyyyys.```````````..
--..--`.-.`.-``..``-.`.-``..``.```.``.```.``````````````````````````````.-`````````.````````..`    ``````.``````````````````````````````````````````````````````````-````...`..+mdyyyyyyyo```````````...
.-.`.-.`--``-.`.-``..``..`..``..``.``..``.```.``.````````````````````````-.`````````` ``  ````   `````````..--``````````````````````````````````````````````````````-```...```.ydyyyyyyyy/```````````...
.--..-.`.-``-.`.-.`.-``..``.``..``.```.``.```.``````.````````````````````.-..```````.``.`````````.:-..`````./:.``````````````````````````````````````````````````.``-``````````/++oosssys-```````````...
.--..--`.-.`.-``-.`.-``..``..`..``.```.``..``.```.``.`````````````````````.-..``````://+:`..`````-....``````::-.`````````````````````````````````````````````````.`..```````````````.....`````````````..
..:..--`.-.`.-.`..`.-.`..``..``.``..``.``..-`.```.``.```.``.```````````````.-.`````:/---o/..``.`..``````````./:-.`````````````.--:---```````````````````.``````````-.-``````````````````````````````````
.+o/..:.`.-``-.`.-``..``..`..``..`..``..``.`...``.``.```.``..```````````````:/:-.``//+/+//...`..``://:-``````-/:-.```````````.++/:-///-`````````````````.```````.`.:-----..`````````````````````````````
`ymm+.:-`.-.`.-`.-.`..``..`.:-/+ossyssso/:-`...``......-osyyhhhys+-``------.-+oo:.-ssoosoo:::-----shyoo-``:---//:.``./oyso-.:so--:::/hs++:----:+osysoo/:::::-::-:syyyhdhhhyyo:::::--````````````````````
`+md:.::..-.`.-``-.`.-``..`.hdmmmmmmmmmmmmo-oyo::hhyyhydmddddmyssd+..dddhyhshhy+/:/ddhhdh+-:::::---....---:-.hhy+-:::/ohhhyyhy-//+:/smddmdhhdhhhyssoosdmdddmmmdddmdsoyhdmmmmmmmdddds```````````````-.```
`-ms/.-/..--`.-.`..`.-.`..``hNNNNNNNNNNNNmodNmmm+NNmmNNNdyd+oosshy...mNmhmNNNNd++++ydmmds:--:++o+/+os+:-...`.mh+::+++ssyddhmm+::+ooymNmdNNmmmdyddssooodmNNNNNNNNNmdoshddNNmmNNmmmmm+```````````````.````
``y++../-`.-.`-.`.-``..`...`sNNNNNNNNNNNNmhNNNNmsdmddddh://::hsom/:/+dmmNNNmmNNhyoo++dmy/--/+yhdddmmmso+//:-:h++/+oosyhhmmmNd+syhdNNNNmmmNNNNNNNNmdsssdmmmNNNNNNNmmhhddyyhhmNmmmmmm:``````````.--:/::::-
``sy+/syysyyysyysyyyyyyys-..+NNNNNmmmdNNNNddyso+++ooss+.----s+/ydddddmmNNNNdyhdmmdhdsssy/:::oyddddmmmmmmmddhhso:----:ydymdmmmhyhdNNNNNmNNNNmdddNNNNmmdmmmmmddddmdh/dmho:/:+hmmmmmNm++++/////:+yhhdddddmm
``-sy/dNNNNNNNNNNNNNNmNNNo/:shmNNNmddmmmmddssssyhhhhhy-`..`.:ohmmy+oydmmmNNmhyhdmmhyhhhdo+//dmmddddmmmmmddmNNh:++-++:shydhddmmmmNNNNNNNNNNho///sdNNNddddmmmmmdddmm-::.`.:+sdNNNmmmmmmmmmmmmm/ydoosoooymm
```-o+/NNNNNNNNNNNNNNNNNNmhhhmNNNNNNMMNNNNmdmmmmdsshd-`````.+/+hs:-:/+dNNNNNNmNmNNmhydmys//omNNmddmNNNNNmdhddo//:-:::odhddddmmmmNNmmNNNMMmyyysyssdNNmmmmNNNNNmmmNN+.``-+ydmmmNNNNNNNNNNNNNNd.-dyosooohNN
```-//.yNNmmmmmmmmmmmmmmmmdhhdNNMMMMMMNNNNMMMNNmddhh+-....-:oooo+ssoosmMMMMNNNNNNNNNNmhssyssmNNNNNNMMMNNy.```-:/+++++yddmddddmdmmmmNNNNNMNddhsyyyyhmmNNNNNdNNNNNNNds+sdmmmmmNNNNNNNNNNNNNNNy``+mso++omNN
```.-/-:ddmmmNNNNNNNNNNNNNNmNdmMMMMMMMMMMMMMMMMNNdy/-:/osyoydoyysso+hmNMMMMNNNNmdddddhssso++dNMMNNMNMNNm.   `.-:::/+/+shmNNNmmhmmmNNNNNNNNdhdhosdy::sddddhomNNNNNNdhydmmmmmmNNNNNNNNNNNNNNNs``:mdysosNNN
````.:::dmdhdddNNNNNddddhmmmNmmmmmmmmNMMMMMNmmmmd/-:+osdddhhoyydhhdddNNNNNmhmmmhhyyyhyyyyysohNNNNNmNmmm/`  `.--/++++:.``:ymNNNmhyymNNNNdyhddmdhyhhs+/hddmmddddmNNdhhhyhdddddmmmdmmmdmmmmNNd+-:syysyydNNN
```.:/+/ymmdddmmmmmmmmdmmmmmNmo+++yooymNNNNmNNms-.:/+ydmdmdyyhdNNmmNdmdmmmdmNmyyyyysssyhdhhyyhdmmmmmmd+.`````-:---:-```   :dmmy+//yNNmmmmmmysosyhho/ommmmmmmmmdddhhhhhmmmmmNNNNNNNNmmmNdds::/shyhhhddmmm
```.:sdyyhmdhhdhyysyyhddmmmmmh/+//++/+ooshmNNm/.-:+ohmdddmmyoyhdmmmmmNNmmdhdmdhhyyyyyhdmmddhhhdddddmmd::``````....`````````./my/..-sosmmmh:`````./shmmddddddmmmmmmdddmmddddmmmmmmmmmmmNmdhsosyyyhhhhdddd
``.-:osooossssssssosoooosyyhhsossssssyddddmNh-.-:/+ymdmmmdmddddmNmdddNmho/-+hmdhdddddddNNdhhyso+ohmmmd:/``````````````......-yNh-..-sNNmd:...````./hhhhhhhhhddddmdmNmmNNNmmmmmmmNNNNNNNNdssosmmNNNNNNNNN
``.-:yyysssssssoooo+++++++++ooshdNNNNNNNNMNs--:/++ohmmmdmmmmddmddddmNNo-````:hNhyhmmmNNNmhho/:...+dNMmhhyyyyyyyyyyyyyyyyhhyhhmmmdhhdNNNdy:+so./o+:/dNNNNNNNNNNNNNNNNmmNmmmddhhddmmmNNNNNy///+hosdNNNNNNN
-:/oosssoo+//::-----.---://::://+yhdmmmmNNN+:/+++so/+ydmmmmmmmmmmmmNNy//:--::+NNmddmmNNmdo-``````.omNNNNNNmmmmmmmmmmmmmmmmmmmNNNMMNmNNNy/-:::`-/:-:+hdddddddmmNNNNmhyo+:----:/+sssyhdysdmmmmmmNNNNNNNNNN
ssyyso//:----...........`...`...-/ooossydmmmssoooo+:-.:+sdmNNNmNNNNNh-:+/--//-oNNmmmmNNNd:-----/+//osmMNNNdhhhyoo-++sysyyyyysdNNMMNmmmNd///+ooo+:-:+NNNNNMNNNNNmyo:-..````````-////+syohNNNNNNmmmmmmmNmN
hhhys+/:-.....`.....`````````````.-/osshddmmhyyyssoo//::...-:--+hNNho:--::-:-./mNmmmNNNmNyssyo/-:-.`.dNNNNNNNNNo/-/.dsNNNNNNNMMMMMNdyhmNmso+//+o+ohNNNNNNMNNNdo:..........``...-::::/oyhNNNNNNNNNNNNNMMM
dddhs+/:-..`````.`````````````````..:++osddyyhhhhyssyooo:::-...+/hNNho+o+++oo+yNNNNNNdhyyyo/://--:/-.dNNNNNNNNNy.:../oNMMMMMMMMMMNNyshhmmhy+/+/+yo+odmNNNNNNh/:---..-............--::/+smNNNNNNNNNNMMMMM
hhys+/:-....-::----.``````````````..-:++/+osyyyhdmddhyyyo++::::--omNNms/++/:+dNNNdyyydmNms/+/ooo+s:-:dNNNNNNm/sd.````mMMMMMMMMNMMNmyssyho++yhhhs/:.`.``.-::/s+/:::---......---..----://osmNNNNNNNNNMMMMN
hys+/:--:////+osyyhhs/--``````````....:/o++osyhhddmmNmdhys+/::+s+odmNMNdyoohNdNNdoymNNmmNNdh+/oo+:..:/oossyhmd:-````.mNNNMMMMMMMNdsoo+/:--///+/:::/s+.`  ``.yo+/::-----/+yhhyssyhysssyhhsyyshNNNNNMMMMNM
yo/:--::-----:::::+osys+-.`..-///+//:--+ssddmmmNNNNNNNNyyso/-::+s+ssNNMNdhmNm+NNm/-osssssssoo///:/:-.`     ``-ys-...-mNNmNNMMNNNNs/:-:::+++++//+/:.`````````ho+//////:+yhhyo++/:o/:-..:/--:/odNNNNMMNNNN
/:------:::///+/::://+/:-.`.-/syyyysssoohhmmmmddddmmNNhsso++/:::+s+/dmNNddddhmNNdo/oosssso:``.:///::.``    ````/ms---oNmdhyyyyyo.``-:/++/::----`````````````ysyhmmddyo+h+syyys+//-....----+/:dmNNNmddmdd
--....--/ydmmmNNmyyy+++:-```-ooo+/::/:/sddmmdhhshdmNNdysso+/+:::/ss:ysdhyhhddNNmddyyhddy-`    `-:-.-.``      `..-y:-..dNhsosss:....-:/+++//-....``..``````.:syhhyhhhdh/++/////::-````..--.--/NNNNNNNNNmd
-...```.-/+sssyyy+ooo:--..``.+syyso+/+//hdmms//+shdmmhy++o+/:+:::os:osyyyyyhdmNmmmmNNm+.``      `.``````     `-...:--.:mdhyss/-::::::/++++/:.`......````..-yh+ssyhyyyh/.-::////--......----./ddmmNNNNNNN
-...``````..-:///::--...`````-yhddhymho/ymNNdhhyhddmmhooso//://-:/o:oos+so//+ohmmNNNms.`````      ``````     `-:------.ommhyy///////:::/+o+:.`.-..........-:s+/+++sooo+...--/osoo+/::-------/yyyyhhhhddm
-..````````````````...````````-/+oossso/yNNNNdddddmmhosso+///:/:-:/-+oooo/:://hmmNNmmy.````````      ``       -+:--:::--shhys++++ooy+::/os+:..-:/--::////::/ohsoo//+ooo+//oss++oyhy+/::----..:/oyyyyyyyy
-...```````````...-:-.`...```..-..----.-:yNNNmhdddmy/+/+o//++o+++oo-/ooss+++sshNNNNmmd/.````.```    ````  ````-y+:-::::-:syh+//++ohmd+-/oso/.`.:/://++++oo/:/hysoo++syhdhhhsoo++ysso+/:----...-`/yhdysss
--............-://////+so+::://::..```..ohNNNNddmmo::::/+/oyyysoyyy/+yyssoosssyNNNNNNNh:.`` `:..``````````````-Ndo/:///::dNd/++osyhmNh:+ss+-```.--..---::+o/:ohsosssyhddhy+/-:///:////:-----...   :o:---
------...----::/::-::/+ooo+osyo++:-.....+NNNNNNNms:-/////+++shhsshhyyhhhhhhssyhNNNNNMMNs-`` `-:.......`   ````.NNNdo+++/:hmo/+oosydmNN+/o+/-```` `.---::::/++/syssyyyyyyyyysoo+//::::/::::---.`        `
------------://:-.....-:/+++++/://:----./NNNNMMm+:::----/++++shyshddhyhddmd+oymNNNNMMMNm:``` `::---..``` ``````dNMMNmdhysds++++sshmmNNy/+/:.` ```````-::/+o+++/yysosyyyyssyyyso+/:://////:::-`
---------:::/+/:::://+//++o+/:-://:::::-oNMNMMd/..:-...-/+ooooyhyydmdddmNNm+/sMMMMNNMMMN/```  `:--.````````````yNMMMMMMMMMmys+osydNMMMmso+:-````````  .:///oss+ohso+::/+syso+++++osoo+++//:.`
---------::/syso/:-:--.`..-/+s+//::///+ymNMNMm+:---::/::/ooooooyhyyhdmmmmNmNy/mMMMMNMMMN-``   `...`````````````oNMMMMMMMMMNy/:-:ohNMMMMy://:-..``````  `....-+sohdys/```.-+syyyhhhyssooo+/.``
----------:++yhddhdmmmmdhyo:-yhs/:///+dNNNMMMNmdho/:-:/oso++o++syhyyhddhhdmMNsomMMMNNMMN-``  ``....````   `````-NMMMMMMNNNmdoooosydddddhyyso+:-...`````     `-/+ohh+```````.-:/shhhysso+-````      ``
----------::::/+o+//:/+oshhhsyso::////NNNNMMNddddhhhysoo+ossso++osyyyyyyydNMMdhyMMMMNMMN/``  ```...````   ``````sNNNmdddddmmmNNNNNNNNNNNNNNNms/:--.```````   ``..-:.`````````..-+sysoo:..``````` ```````
------------...---::::::///+/::::://ohNNNNMMmdhyyssoooooooo++sso+ssyyyhdmNMMMMMNMMMMMMMN/`  `````.````     `````oNddmmNNNNNNNNNNNNNNNNNNNNNNNNhs/:--..`````  ``  ``.``````````..-/ys+-...```````````````
-----------.....----::::::::----://sNNNNNNMNmdhhyysoo+++++oyyssssosyyhyhdNMMMMMMMMMmdhys.``````..-----.`   `` ``/mmmNNNNNNNNNNNNmddddhddmNNNNNNmdo::--..````````````....```````..omhy+-````````...``````
:--------................------:/+yNNNNNNNNNmddhhhysoo+++++ohhhhhhdddddNMMMMMMMMMMmsooo-`.````.oyyhhyyyo+- ```.`+mmmNNNNNNNNNNNNNmdsoo+syymNNNNNNmy+/:--...``````````.....```````odddmdo:````.-.````````
::---------........`...`....--:+sdNNNNNmNNNNmmmdddhhysso++++osyyyddmNNMMMMMMMMMMMMMMMMN/``````smmddddddddh:`````/mmNNNNNNNNNNNMNNNhoyossdmdNNNNNNNNms+/::-.....``.```.......`````-dmmmmdho:..`````.`````
::--------------------------:/odNNNNNmmmNNNNNNmmmmddhhysso++oss::ymmNMMNMMNNMMMMMMMMMMN:`.``.+mmmmmmmNNmmmms.```.mNNNNNNNNNNMMMMNdhyddhmdNNNNNNNNNNNNmyo//:-----..`.``.......`````ymdhyso/:-.......```
:::----------::::::::::////+sdNNNNNNmddmmNNNNNNNNmmmmddhyyssosy-`/mNNNNNh+:/mhosNMMMMMd.+-`.sNNmdmmmmNNNNNNNo:-..yNNNNNNNNMMMMMMMNNNNNNNNNNNNNNNNNNNNNNmhs++/::://:-..........````+yyhhs+:---...````  ``
.-::--::::::::::::://///oydmNNNNNNNmdhddmmmmNNMMNNNNNmmmmddhhhy.`.dNNmh:`.+y/.-oymMMMMmsm:..yNNmmNNmNNNMMNNNNy/:-+NNNNNNMMMMMMMMNNNNNNNNNNNNNNNMMMMMNNNNNNdyso+//+oo+:-.-...``..``+hdmmh/....`````````..
  `-::::/:::::::///++++sdmmNNNNNNNNmhyhhdhdddmmNNNMMMNNNNNNmmmd-``:ys:.``//.`-:./dMMMmsyNo.`/NNNNNNmNNMMMMMMNNmy++mNNMMNMMMMMMMNNNNNNNMMMMMMMMMMMMMMMMMMMNNNNmhysosyyyys/-..````.-sshhdo.`````.....-----
    `.-/+++++++++oooo+shdmmmNNNNNNNmdhhhhhhhhhhdmNNNMNNNNNNNNmmo.``````````..`-shsmMMmhyNmyydNNNNNNNNNMMMMMMMMMMNNMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmmmmmmmmo-..``.-omhsyh/`..---------....
     ```./oosooooooo+oo//+oshdmNNNNNmmddhdhhhddddmmNNmmmmmmmNNmd:.```````````:o/./mMNNMMNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMMMMMMMMMNNNNNNm+...`/oydmdsy+:::---........``
``    `````-/+ooooooosyo.   `./sdNNNNNNNNNNNNNNNNNNNNmmdddmmmmmmo-.``````````..:yNNMNNNMNNNNNNNNNNNNNNMMMMMMMMMMMMNNMMMMMMNNMMMMMMMMMMMMMMMMMMMNNNNNNNNNNMMMMMMMMMMMMMNNNNm:...ydsdmmms/::--.......`````
        ``````.:ssooyysy+`      ./hmmmmmmNNNNNNNNNNNNNmmmddmmmmy-....``````.-/ymmmmNMNNNMNNNNNNNNNNNNNNMMMMMMMNNNNmmMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNMMMMMMMMMMMMMMMMNNh-..ymdydmmh/--..````````````
        ```````-oo+smdyyy/`       `:osyyydmddddddddddddddddmmh/.```..`...-:+ydddddmmNNNNNNNNNNNNNNNNNNNNMNNNNNmmmmddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMNNNMMMMMMMNNNNNs.:sdNdyddy/-...````````````
             `-oo+omNNmdhy:`        `:yhhddddmmmmmmNNNNNNNNms.    ``..-/sddyhhddddddmNNmmNNNNNNNNNNNNmNNNNNNNNNmmmmmNMMMMMMMMMMMMNNNNNNNNNNNNNNNNmmmmmddddddhhysosyhmNso+++++-ohhmNhyds:-..`````````````
            `-oo++ymNNNNmhs.          /NNNNNNNNNNNNNNNNNNNd:        `.+dNNNyyhdddddmmmNNNNNNNNmmmmmmmddddddddhhhyyyyyyhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyysssssso+/////s/://++++yNydmNyys-.```.......`````
            .//:--:smNNNNmh:`         `dNNNNNNNNNNNNNNNNms`        ```yNNNNhhhhhhhhhhhhhhhyymdsso+//:--...``````...--://++ooossssssyyyyyyyyyhhhhhhhhhhhhhhhddddmmmmNNNNMNNNNNNymmydmNyy-................
                   .hmNNNNm/`          ommmmmmmmmmddmddy-         ````+NNNNssssssssssssssssodyo+//:--.....```.-:::://+++oooosssssyyhhddddmmmmmmmmNNNNNNNNMMMMMMMMMMMMMMMMMMMMMhdNdhdmhy+-----...........
                    /dmNNNN+``         `sdddddddddddhh+`       ``````:dNNNNsssssssssssssoooodyo++//:--........ydddhddddmmmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhmNydhyys...-----------..
                    `ommNNNNs.`        `/dmmmmmmmmmmh-`       ``````oNNNNNNsoooooooooooooooomyoo++//:---......hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdmhdmmsssyy-..-.........---
                     :ymmNNNNd/`       `-mNNNNNNNmh+`       ``````.yNNNNNNMyoooooossssssssssmyooo++//:::------dMMMMMMMMMMMMNNNNNNNNNNNNMMMMMMMMMMMMNNNMNNNNNNNNNNNNMMMMMMMMMMdmNymNh+osy/.`......-------
                     .ydmNNmNNh:`      ``yNNNNNNh-           ````:dNNNNNNNNhsssssssyyyyyyysymysooo++//::------mMMMMMMMMMNNNNNmNmmmmmmmmmmmNmmmmmmmmmmmmmmNNNMNNNNNNNNNMMMMMMMmdNydmy/oss+...............
                      sdmmmmmNmd:`     ` :mmmmh+`    ``     ````/mNNNNNNNNNdsssssssyyyyyyssyNyssoo++//:::-----mMMMMMMMMMNNmhyhhdddddddddmNMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMNNhmmhms:+so+-```...........
                      -hydmmmmNmh-`      `hmh+`       ````````.sNNNNNNNNNNNdssssssssssssssssmsooo+++//:::-----mMMMMMMMMMMNmmddmmmmmmmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmNhmNhh///ss/:.``...........
                      `ssydmmmNNmh-`      /:`        `` `````.hNNNNNNNNNNNNmsssssssssssssssymsoooo++//::---..-mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdNddNNo+++ss+:..............
                       :hoydmmmNNNh-`     `           ``````-dNNNNNNNNNNNNNmsssssssssssssssymssooo+++//:---..-NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdmNhmd///oos+/.``...........